### ISSUE TITLE
LGPL is problematic for Rust programs

### ISSUE THREAD

**Issue by seekstar** [Fairglow/index-list#2]
<https://github.com/rpm-software-management/librpm.rs/issues/21>

>The LGPL is somewhat problematic for Rust programs: due to Rust’s transitive recompilation requirements, it essentially becomes equivalent to the GPL in many cases.

>MPLv2 is the closest thing to LGPL that is convenient in Rust. Source files of the original work are protected (if you modify them, the modifications need to be available under the MPLv2 license also) but derivative works are not restricted.

>It's an LGPL-lookalike that draws the boundaries in terms of source files rather than how libraries are linked together, essentially.

>That would provide more protections than either MIT or Apache, but be less of a compliance headache than LGPL.

How about switching to MPLv2?

**Comment by Fairglow** [comment]
Thanks you for your request and I'm happy to oblige

**Comment by seekstar** [comment]
Did you forget to publish the new version to crates.io? The crate on crates.io is still the version licensed under LGPL.

**Comment by ryoqun** [comment]
@Fairglow hey, i also stumbled on this issue. could you publish a new version?

**Comment by Fairglow** [comment]
Sorry, yes, apparently I did. Thanks for the reminder. I've published version ` 0.2.10` to [crates.io](https://crates.io/crates/index_list) including the `with_capacity` method and with ` MPL-2.0` license.

Thanks for the PR @seekstar and the reminder @ryoqun !
